# Header Menu
menu:
  Home: /
  API Documentation: /documentation/
  Blog: /archives/ # can set archive-dir in root config to custom value
  Contact: /contact/
  About: /about/
author: Bogdan Mustiata

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname:
google_analytics:
swiftype_install_key:

# Social
social:
  github: https://github.com/germaniumhq
  twitter: https://twitter.com/bmst
  facebook: https://www.facebook.com/ptsteadman
  rss: atom.xml
  docker: https://linkedin.com/in/ptsteadman
  linkedin: https://linkedin.com/in/ptsteadman
  stackoverflow: http://stackoverflow.com/users/2480493/patrick-steadman

# Miscellaneous
color_scheme: green   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_widget_id: "727241878911983616" # as a string, from https://twitter.com/settings/widgets
twitter_username: bmst # twitter username without the @
default_author: Anonymous

about: Computer Lab is a software development and marketing company based in Brooklyn, New York. <br><br> Computer Lab was founded in 2015, and is focused on so on and so forth.
phone: +43 660 1453541
email: germaniumhq@gmail.com
address_1: 1120, Vienna
address_2: Vienna
address_3: Austria
skype:
lat: 40.715911
long: -73.962147
